foreign-key:
  # The column in the 'metrics' table we want to populate.
  vm_id:
    # Look for a matching record in this table.
    from-table: vm

    # We will use the 'vm_id' from the 'vm' table for our foreign key.
    from-column: vm_id

    # The column in the 'vm' table that we will use to find the match.
    to-column: vm_id

    # The Prometheus label on the incoming metric that contains the value
    # to match against. By using 'vm_id' as the label, we ensure a
    # perfect, unique match every time.
    on-label: vm_id